# Generated by Django 5.2.1 on 2025-07-07 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.BigIntegerField(null=True)),
                ('client_name', models.CharField(max_length=256, null=True)),
                ('module_name', models.CharField(max_length=256, null=True)),
                ('sub_module', models.CharField(max_length=256, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded_excel', models.FileField(default='', upload_to='downloaded_excel')),
                ('uploaded_excel', models.FileField(default='', upload_to='uploaded_excel')),
                ('url', models.URLField(null=True)),
                ('created_by', models.CharField(max_length=256, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test_run_process_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testcase_code', models.CharField(max_length=256, null=True)),
                ('test_implement_status', models.CharField(max_length=256, null=True)),
                ('percentage', models.TextField(max_length=256, null=True)),
                ('Process_status', models.SmallIntegerField(default=0)),
                ('Scenario_names', models.TextField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256, null=True)),
                ('Testcase_code', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('screenshoot', models.TextField(blank=True, max_length=200, null=True)),
                ('Testcase_Result', models.CharField(blank=True, max_length=16, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=256, null=True)),
                ('inputdata', models.TextField(blank=True, null=True)),
                ('outputdata', models.TextField(blank=True, null=True)),
                ('Module', models.CharField(max_length=256, null=True)),
                ('Toast_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('code', models.TextField(blank=True, max_length=200, null=True)),
                ('Test_scnarios', models.TextField(blank=True, max_length=200, null=True)),
                ('percentage', models.TextField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase_Scenario_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256, null=True)),
                ('Project_module', models.CharField(max_length=256, null=True)),
                ('Testcase_scenario_name', models.CharField(max_length=256, null=True)),
                ('Testcase_scenario_template', models.TextField(blank=True, null=True)),
                ('environment', models.CharField(max_length=256, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(max_length=256, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_by', models.CharField(max_length=256, null=True)),
                ('run_status', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase_Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testcase_code', models.CharField(max_length=256, null=True)),
                ('Testcase_template_input', models.TextField(blank=True, null=True)),
                ('module', models.CharField(max_length=256, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=256, null=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(max_length=256, null=True)),
                ('environment', models.CharField(max_length=256, null=True)),
                ('testcase_scn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NF_Automation.testcase_scenario_template')),
            ],
        ),
    ]
