# Generated by Django 5.2.1 on 2025-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NF_Automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase_run',
            name='Process_status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcase_run',
            name='percentage',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='testcase_run',
            name='test_implement_status',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
