# Generated by Django 5.2.1 on 2025-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NF_Automation', '0003_testcase_result_test_implement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase_run',
            name='clientname',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
