# Generated by Django 5.2.1 on 2025-07-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NF_Automation', '0004_testcase_run_clientname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automation_History',
        ),
        migrations.AddField(
            model_name='testcase_scenario_template',
            name='environment_url',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
