# Generated by Django 5.2.1 on 2025-07-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NF_Automation', '0005_delete_automation_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase_run',
            name='environment_url',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
