# Generated by Django 5.2.7 on 2025-11-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NF_Automation', '0006_testcase_run_environment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase_scenario_template',
            name='scenario_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
